### ISSUE TITLE
什么原因不知道

### ISSUE THREAD

**Issue by ivantree** [bmfe/eros-yanxuan-demo-v2#7]
### 简略的描述你的问题。
> 例：图片上传导致系统崩溃。
### 环境信息 
> 例子：
> * 开发平台：darwin\/windows/linux
> * node 版本：8.x.x
> * npm 版本：5.x.x
> * 调试类型：模拟器/真机
> * 调试系统版本: ios 8
> * 开发工具及其版本 xcode 9

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> 例：bmImage module 中不支持传递参数的类型，导致的崩溃。
### 什么场景下会复现这个问题，复现率是多少。
> 例：百分百复现，调用即复现。

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
> 答：
![image](https://user-images.githubusercontent.com/9014680/41297152-1d959c76-6e91-11e8-86f5-2b3d7d3a873c.png)

**Comment by PerseveranceZ** [comment]
@ivantree 可以贴一下调用代码吗

**Comment by ivantree** [comment]
$ git clone https://github.com/bmfe/eros-yanxuan-demo-v2.git eros-yanxuan
$ cd eros-yanxuan
$ npm i

Android 需要自行导入项目

运行就出现这个问题了
@PerseveranceZ

**Comment by PerseveranceZ** [comment]
@ivantree 执行  eros pack android 试一下
