### ISSUE TITLE
安卓运行报错。找不到 本地 资源, 

### ISSUE THREAD

**Issue by youxdd** [bmfe/eros-yanxuan-demo-v2#9]
### 简略的描述你的问题。
> 例：安卓运行报错。
### 环境信息 
> 例子：
> * 开发平台：darwin 10.13.6
> * node 版本：8.11.3
> * npm 版本：6.2.0
> * 调试类型：真机/模拟器 
> * 调试系统版本: android 8.0
> * 开发工具及其版本 android studio  3.1.3

![screenshot_20180802-110101](https://user-images.githubusercontent.com/17402720/43560179-dd52d7a2-9643-11e8-80eb-580875a54327.jpg)

**Comment by PerseveranceZ** [comment]
eros pack 试一下呢

**Comment by qld-cf** [comment]
@PerseveranceZ 可以
